Repository neuland-ingolstadt/neuland.app, pull requests merged in 2023-10, with the labels that each got.

#327 ♿️ improve card colors
  rogue-thi-app/styles/Home.module.css
  rogue-thi-app/styles/Mensa.module.css
  rogue-thi-app/styles/Mobility.module.css
Labels: user experience

#349 LanguageFood on develop branch
  rogue-thi-app/components/cards/FoodCard.jsx
  rogue-thi-app/components/modal/LanguageModal.jsx
  rogue-thi-app/lib/hooks/food-filter.js
  rogue-thi-app/pages/food.jsx
  rogue-thi-app/public/locales/de/personal.json
  rogue-thi-app/public/locales/en/personal.json
Labels: hackathon-ws23/24

#354 Room availability
  rogue-thi-app/components/RoomMap.jsx
  rogue-thi-app/lib/backend-utils/rooms-utils.js
  rogue-thi-app/public/locales/de/rooms.json
  rogue-thi-app/public/locales/en/rooms.json
  rogue-thi-app/styles/RoomMap.module.css
Labels: new-feature
