Repository neuland-ingolstadt/neuland.app, pull requests merged in 2023-03, with the labels that each got.

#193 Improves Personal Page
  rogue-thi-app/pages/personal.js
Labels: bug, user experience

#211 fixes wrong routing
  rogue-thi-app/pages/personal.js
Labels: bug

#212 Improves display of soups
  rogue-thi-app/pages/food.js
Labels: user experience

#213 Simplifies Pride Theme
  rogue-thi-app/scss/themes/pride.scss
  rogue-thi-app/styles/AppNavbar.module.css
Labels: user experience

#210 🥗 Swipe-able weekly food tabs
  rogue-thi-app/components/SwipeableTabs.js
  rogue-thi-app/lib/backend-utils/food-utils.js
  rogue-thi-app/lib/date-utils.js
  rogue-thi-app/pages/food.js
  rogue-thi-app/styles/Mensa.module.css
Labels: user experience

#227 🪄 Suggest rooms based on timetable in room card
  rogue-thi-app/components/allCards.js
  rogue-thi-app/components/cards/RoomCard.js
  rogue-thi-app/lib/backend-utils/rooms-utils.js
Labels: new-feature

#228 🪲 Wrong display of current week in food.js #225
  rogue-thi-app/components/SwipeableTabs.js
  rogue-thi-app/lib/backend-utils/food-utils.js
  rogue-thi-app/lib/date-utils.js
  rogue-thi-app/pages/food.js
  rogue-thi-app/styles/Mensa.module.css
Labels: bug
