Repository neuland-ingolstadt/neuland.app, pull requests merged in 2023-07, with the labels that each got.

#300 Fixes language cookie deletion on browser session end
  rogue-thi-app/components/modal/LanguageModal.js
Labels: bug

#302 Improve translation fallback and development
  rogue-thi-app/lib/backend-utils/translation-utils.js
  rogue-thi-app/package-lock.json
  rogue-thi-app/package.json
Labels: bug, high priority

#308 🐛 Fix canisius category and unify settings label
  rogue-thi-app/pages/food.js
  rogue-thi-app/public/locales/de/personal.json
  rogue-thi-app/public/locales/en/personal.json
Labels: bug

#316 Update files to JSX format
  rogue-thi-app/android/.gitkeep
  rogue-thi-app/components/RoomMap.jsx
  rogue-thi-app/components/SwipeableTabs.jsx
  rogue-thi-app/components/TheMatrixAnimation.jsx
  rogue-thi-app/components/allCards.jsx
  rogue-thi-app/components/cards/BaseCard.jsx
  rogue-thi-app/components/cards/CalendarCard.jsx
  rogue-thi-app/components/cards/ElectionPrompt.jsx
  rogue-thi-app/components/cards/EventsCard.jsx
  rogue-thi-app/components/cards/ExamsCard.jsx
  rogue-thi-app/components/cards/FoodCard.jsx
  rogue-thi-app/components/cards/InstallPrompt.jsx
  rogue-thi-app/components/cards/MobilityCard.jsx
  rogue-thi-app/components/cards/RoomCard.jsx
  rogue-thi-app/components/cards/SurveyPrompt.jsx
  rogue-thi-app/components/cards/TimetableCard.jsx
  rogue-thi-app/components/modal/DashboardModal.jsx
  rogue-thi-app/components/modal/FilterFoodModal.jsx
  rogue-thi-app/components/modal/LanguageModal.jsx
  rogue-thi-app/components/modal/PersonalDataModal.jsx
  rogue-thi-app/components/modal/ThemeModal.jsx
  rogue-thi-app/components/page/AppBody.jsx
  rogue-thi-app/components/page/AppContainer.jsx
  rogue-thi-app/components/page/AppNavbar.jsx
  rogue-thi-app/components/page/AppTabbar.jsx
  rogue-thi-app/lib/backend-utils/mobility-utils.jsx
  rogue-thi-app/lib/date-utils.jsx
  rogue-thi-app/pages/_app.jsx
  rogue-thi-app/pages/become-hackerman.jsx
  rogue-thi-app/pages/calendar.jsx
  rogue-thi-app/pages/debug.jsx
  rogue-thi-app/pages/events.jsx
  rogue-thi-app/pages/food.jsx
  rogue-thi-app/pages/grades.jsx
  rogue-thi-app/pages/imprint.jsx
  rogue-thi-app/pages/index.jsx
  rogue-thi-app/pages/lecturers.jsx
  rogue-thi-app/pages/library.jsx
  rogue-thi-app/pages/login.jsx
  rogue-thi-app/pages/mobility.jsx
  rogue-thi-app/pages/personal.jsx
  rogue-thi-app/pages/rooms/index.jsx
  rogue-thi-app/pages/rooms/list.jsx
  rogue-thi-app/pages/rooms/search.jsx
  rogue-thi-app/pages/rooms/suggestions.jsx
  rogue-thi-app/pages/timetable.jsx
Labels: code-quality
